import 'package:flutter/material.dart';
import 'package:test1/features/home/Data/models/lines_model.dart';
import 'package:test1/features/home/Data/models/ride_model.dart';
import 'package:test1/features/home/presentation/views/all_lines_view/widgets/lines_item2.dart';

class AllLinesListView extends StatelessWidget {
  const AllLinesListView({super.key});

  @override
  Widget build(BuildContext context) {
    List<LineModel> lineModel = [
      LineModel(
        lineName: 'Zayed Lines ',
        rides: [
          RideModel(
            lineName: "Zayed Line 1",
            numberOfstations: "5",
            linePrice: "250 EGP",
            departureArea: "Talaat Harb",
            departureTime: "7:30 PM",
            duration: "2 Hours",
            arrivalTime: "8:30 PM",
            arrivalArea: "Ramses",
            departureStation: "Bab AL louq",
            arrivalStation: "Mobile station",
          ),
          RideModel(
            lineName: "Zayed Line 2",
            numberOfstations: "12",
            linePrice: "250 EGP",
            departureArea: "Talaat Harb",
            departureTime: "8:30 PM",
            duration: "2 Hours",
            arrivalTime: "10:30 PM",
            arrivalArea: "Ramses",
            departureStation: "Bab AL louq",
            arrivalStation: "Mobile station",
          ),
          RideModel(
            lineName: "Zayed Line 1 night",
            numberOfstations: "5",
            linePrice: "250 EGP",
            departureArea: "Talaat Harb",
            departureTime: "10:30 PM",
            duration: "2 Hours",
            arrivalTime: "11:30 PM",
            arrivalArea: "Ramses",
            departureStation: "Bab AL louq",
            arrivalStation: "Mobile station",
          ),
          RideModel(
            lineName: "Zayed Line 4",
            numberOfstations: "5",
            linePrice: "250 EGP",
            departureArea: "Talaat Harb",
            departureTime: "7:30 PM",
            duration: "2 Hours",
            arrivalTime: "8:30 PM",
            arrivalArea: "Ramses",
            departureStation: "Bab AL louq",
            arrivalStation: "Mobile station",
          ),
        ],
      ),
      LineModel(
        lineName: 'Ramses Lines ',
        rides: [
          RideModel(
            lineName: "Zayed Line 1",
            numberOfstations: "5",
            linePrice: "250 EGP",
            departureArea: "Talaat Harb",
            departureTime: "7:30 PM",
            duration: "2 Hours",
            arrivalTime: "8:30 PM",
            arrivalArea: "Ramses",
            departureStation: "Bab AL louq",
            arrivalStation: "Mobile station",
          ),
          RideModel(
            lineName: "Zayed Line 2",
            numberOfstations: "12",
            linePrice: "250 EGP",
            departureArea: "Talaat Harb",
            departureTime: "8:30 PM",
            duration: "2 Hours",
            arrivalTime: "10:30 PM",
            arrivalArea: "Ramses",
            departureStation: "Bab AL louq",
            arrivalStation: "Mobile station",
          ),
          RideModel(
            lineName: "Zayed Line 1 night",
            numberOfstations: "5",
            linePrice: "250 EGP",
            departureArea: "Talaat Harb",
            departureTime: "10:30 PM",
            duration: "2 Hours",
            arrivalTime: "11:30 PM",
            arrivalArea: "Ramses",
            departureStation: "Bab AL louq",
            arrivalStation: "Mobile station",
          ),
          RideModel(
            lineName: "Zayed Line 4",
            numberOfstations: "5",
            linePrice: "250 EGP",
            departureArea: "Talaat Harb",
            departureTime: "7:30 PM",
            duration: "2 Hours",
            arrivalTime: "8:30 PM",
            arrivalArea: "Ramses",
            departureStation: "Bab AL louq",
            arrivalStation: "Mobile station",
          ),
        ],
      ),
      LineModel(
        lineName: 'Hosary Lines ',
        rides: [
          RideModel(
            lineName: "Zayed Line 1",
            numberOfstations: "5",
            linePrice: "250 EGP",
            departureArea: "Talaat Harb",
            departureTime: "7:30 PM",
            duration: "2 Hours",
            arrivalTime: "8:30 PM",
            arrivalArea: "Ramses",
            departureStation: "Bab AL louq",
            arrivalStation: "Mobile station",
          ),
          RideModel(
            lineName: "Zayed Line 2",
            numberOfstations: "12",
            linePrice: "250 EGP",
            departureArea: "Talaat Harb",
            departureTime: "8:30 PM",
            duration: "2 Hours",
            arrivalTime: "10:30 PM",
            arrivalArea: "Ramses",
            departureStation: "Bab AL louq",
            arrivalStation: "Mobile station",
          ),
          RideModel(
            lineName: "Zayed Line 1 night",
            numberOfstations: "5",
            linePrice: "250 EGP",
            departureArea: "Talaat Harb",
            departureTime: "10:30 PM",
            duration: "2 Hours",
            arrivalTime: "11:30 PM",
            arrivalArea: "Ramses",
            departureStation: "Bab AL louq",
            arrivalStation: "Mobile station",
          ),
          RideModel(
            lineName: "Zayed Line 4",
            numberOfstations: "5",
            linePrice: "250 EGP",
            departureArea: "Talaat Harb",
            departureTime: "7:30 PM",
            duration: "2 Hours",
            arrivalTime: "8:30 PM",
            arrivalArea: "Ramses",
            departureStation: "Bab AL louq",
            arrivalStation: "Mobile station",
          ),
        ],
      ),
      LineModel(
        lineName: 'Giza Lines',
        rides: [
          RideModel(
            lineName: "Zayed Line 1",
            numberOfstations: "5",
            linePrice: "250 EGP",
            departureArea: "Talaat Harb",
            departureTime: "7:30 PM",
            duration: "2 Hours",
            arrivalTime: "8:30 PM",
            arrivalArea: "Ramses",
            departureStation: "Bab AL louq",
            arrivalStation: "Mobile station",
          ),
          RideModel(
            lineName: "Zayed Line 2",
            numberOfstations: "12",
            linePrice: "250 EGP",
            departureArea: "Talaat Harb",
            departureTime: "8:30 PM",
            duration: "2 Hours",
            arrivalTime: "10:30 PM",
            arrivalArea: "Ramses",
            departureStation: "Bab AL louq",
            arrivalStation: "Mobile station",
          ),
          RideModel(
            lineName: "Zayed Line 1 night",
            numberOfstations: "5",
            linePrice: "250 EGP",
            departureArea: "Talaat Harb",
            departureTime: "10:30 PM",
            duration: "2 Hours",
            arrivalTime: "11:30 PM",
            arrivalArea: "Ramses",
            departureStation: "Bab AL louq",
            arrivalStation: "Mobile station",
          ),
          RideModel(
            lineName: "Zayed Line 4",
            numberOfstations: "5",
            linePrice: "250 EGP",
            departureArea: "Talaat Harb",
            departureTime: "7:30 PM",
            duration: "2 Hours",
            arrivalTime: "8:30 PM",
            arrivalArea: "Ramses",
            departureStation: "Bab AL louq",
            arrivalStation: "Mobile station",
          ),
        ],
      ),
      LineModel(
        lineName: 'Zayed Lines ',
        rides: [
          RideModel(
            lineName: "Zayed Line 1",
            numberOfstations: "5",
            linePrice: "250 EGP",
            departureArea: "Talaat Harb",
            departureTime: "7:30 PM",
            duration: "2 Hours",
            arrivalTime: "8:30 PM",
            arrivalArea: "Ramses",
            departureStation: "Bab AL louq",
            arrivalStation: "Mobile station",
          ),
          RideModel(
            lineName: "Zayed Line 2",
            numberOfstations: "12",
            linePrice: "250 EGP",
            departureArea: "Talaat Harb",
            departureTime: "8:30 PM",
            duration: "2 Hours",
            arrivalTime: "10:30 PM",
            arrivalArea: "Ramses",
            departureStation: "Bab AL louq",
            arrivalStation: "Mobile station",
          ),
          RideModel(
            lineName: "Zayed Line 1 night",
            numberOfstations: "5",
            linePrice: "250 EGP",
            departureArea: "Talaat Harb",
            departureTime: "10:30 PM",
            duration: "2 Hours",
            arrivalTime: "11:30 PM",
            arrivalArea: "Ramses",
            departureStation: "Bab AL louq",
            arrivalStation: "Mobile station",
          ),
          RideModel(
            lineName: "Zayed Line 4",
            numberOfstations: "5",
            linePrice: "250 EGP",
            departureArea: "Talaat Harb",
            departureTime: "7:30 PM",
            duration: "2 Hours",
            arrivalTime: "8:30 PM",
            arrivalArea: "Ramses",
            departureStation: "Bab AL louq",
            arrivalStation: "Mobile station",
          ),
        ],
      ),
      LineModel(
        lineName: 'Giza Lines ',
        rides: [
          RideModel(
            lineName: "Zayed Line 1",
            numberOfstations: "5",
            linePrice: "250 EGP",
            departureArea: "Talaat Harb",
            departureTime: "7:30 PM",
            duration: "2 Hours",
            arrivalTime: "8:30 PM",
            arrivalArea: "Ramses",
            departureStation: "Bab AL louq",
            arrivalStation: "Mobile station",
          ),
          RideModel(
            lineName: "Zayed Line 2",
            numberOfstations: "12",
            linePrice: "250 EGP",
            departureArea: "Talaat Harb",
            departureTime: "8:30 PM",
            duration: "2 Hours",
            arrivalTime: "10:30 PM",
            arrivalArea: "Ramses",
            departureStation: "Bab AL louq",
            arrivalStation: "Mobile station",
          ),
          RideModel(
            lineName: "Zayed Line 1 night",
            numberOfstations: "5",
            linePrice: "250 EGP",
            departureArea: "Talaat Harb",
            departureTime: "10:30 PM",
            duration: "2 Hours",
            arrivalTime: "11:30 PM",
            arrivalArea: "Ramses",
            departureStation: "Bab AL louq",
            arrivalStation: "Mobile station",
          ),
          RideModel(
            lineName: "Zayed Line 4",
            numberOfstations: "5 ",
            linePrice: "250 EGP",
            departureArea: "Talaat Harb",
            departureTime: "7:30 PM",
            duration: "2 Hours",
            arrivalTime: "8:30 PM",
            arrivalArea: "Ramses",
            departureStation: "Bab AL louq",
            arrivalStation: "Mobile station",
          ),
        ],
      ),
    ];
    return Padding(
      padding: const EdgeInsets.symmetric(horizontal: 20.0),
      child: ListView.builder(
        itemBuilder: (context, index) {
          return Padding(
            padding: const EdgeInsets.only(bottom: 20.0),
            child: LinesItem2(
              lineModel: lineModel[index],
              linesNumber: lineModel[index].rides!.length.toString(),
            ),
          );
        },
        itemCount: lineModel.length,
      ),
    );
  }
}
